name: Mirror to Personal GitHub

on:
  push:
    branches:
      - main

jobs:
  mirror_to_github:
    # เพิ่มบรรทัดนี้: ป้องกันไม่ให้โค้ดไปรันซ้ำแล้วพังที่ฝั่ง Personal
    if: github.repository == 'thanawat-wlb/sck-shopping-mall-playwright'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to mirror repository
        env:
          DEST_GITHUB_TOKEN: ${{ secrets.DESTINATION_PERSONAL_GITHUB_TOKEN }}
          DEST_GITHUB_USERNAME: "thanawat-hub" 
          # แก้ไข 1: เปลี่ยนชื่อ Repo ให้ตรงกับปลายทาง
          DEST_REPO: "sck-shopping-mall-playwright" 
        run: |
          echo "Start mirroring branch $GITHUB_REF_NAME to GitHub..."
          
          # อีเมลสำหรับตัว Runner ของ GitHub Action (ไม่ต้องแก้อะไรตรงนี้)
          git config --global user.email "bunysiththiphic@gmail.com"
          git config --global user.name "thanawat-hub"
          
          git remote add mirror https://${DEST_GITHUB_USERNAME}:${DEST_GITHUB_TOKEN}@github.com/${DEST_GITHUB_USERNAME}/${DEST_REPO}.git
          
          git push mirror HEAD:refs/heads/$GITHUB_REF_NAME