name: Mirror to Personal GitHub

# สั่งให้ทำงานเมื่อมีการ push หรือ merge โค้ดเข้ามาที่ branch 'main'
on:
  push:
    branches:
      - main

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to mirror repository
        env:
          # ดึงกุญแจบ้าน Personal ที่เราฝากไว้ในตู้เซฟฝั่ง Work มาใช้
          DEST_GITHUB_TOKEN: ${{ secrets.DESTINATION_GITHUB_TOKEN }}
          # ใส่ Username ของบัญชี Personal
          DEST_GITHUB_USERNAME: "thanawat-hub" 
          # ใส่ชื่อ Repo ของบัญชี Personal
          DEST_REPO: "wlb-playwright" 
        run: |
          echo "Start mirroring branch $GITHUB_REF_NAME to GitHub..."
          
          git config --global user.email "bunysiththiphic@gmail.com"
          git config --global user.name "thanawat-hub"
          
          # ใช้กุญแจ (Token) ที่ดึงมา ยืนยันตัวตนตอนแอด URL ปลายทาง
          git remote add mirror https://${DEST_GITHUB_USERNAME}:${DEST_GITHUB_TOKEN}@github.com/${DEST_GITHUB_USERNAME}/${DEST_REPO}.git
          
          git push mirror HEAD:refs/heads/$GITHUB_REF_NAME